apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/npm/0.1/npm.yaml
- build-bot.ServiceAccount.yaml
- create-configuration.Task.yaml
- deploy.Task.yaml
- docker.Secret.yaml
- webhook-receiver.EventListener.yaml
- nextjs.Pipeline.yaml
